### PR TITLE
Resolved issue of Home screen widget

### PR DESCRIPTION
**Pull request by Abhishekmnnit6022**
My  Name is Abhishek Rastogi 20238030 
Github user name -Abhishekmnnit6022 

I have resolved the issue of Home Screen widget .I have created widget with the mentioned features.

kindly accept my pull request.

Thanks

### CODE REVIEW

**Comment by Pra-San** [comment]
@Abhishekmnnit6022  open this in the contrihub repository not my repository.

**Comment by Abhishekmnnit6022** [comment]
I don't get the point

**Comment by Pra-San** [comment]
Go to the place where you found the issue. This is a reposiotory in my profile, the contrihub org is where the event is taking place.

**Comment by Pra-San** [comment]
https://github.com/ContriHUB/Music-Player/issues/2

**Comment by Abhishekmnnit6022** [comment]
kindly help me i have done the given steps

Forked the github repo from contrihub repo

Cloned the repo

Created new branch and make the changes

Commit it in the repo

Create a pull request it that repo


Now can you please tell me where i am wrong. Help me.

Thanks

**Comment by Pra-San** [comment]
You created a pull request in the wrong repository. Make a pull request in the contrihub repository not in this one. This is not the contrihub repository.

**Comment by Pra-San** [comment]
https://github.com/ContriHUB/Music-Player
This is the actual repo

**Comment by Abhishekmnnit6022** [comment]
Sir how to correct the pr link . I have make a pull request in actual repo now how to submit that link?

**Comment by Pra-San** [comment]
Forget about that and continue in the new PR.

**Pull request closed without merging**
